FROM node:15.10-alpine
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json

RUN npm install

ENV NODE_ENV production

COPY . /usr/src/app
RUN npm run build --production

#########
# FINAL #
#########
EXPOSE 3000
CMD ["node_modules/.bin/next", "start"]