[tool.black]
line-length = 85
exclude = '''   
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | .pytest_cache
    | buck-out
    | build
    | dist
    | alembic
  )/
)
'''